### PR TITLE
Fix broken struct field casing

### PR DESCRIPTION
**Pull request by fffinkel**
Mistake in casing breaks library and tests, simply fix the casing.

### CODE REVIEW

**Comment by fffinkel** [comment]
The app is currently broken, this commit fixes it.

**Review by Admiral-Piett — APPROVED** [review]

**Comment by Admiral-Piett** [comment]
Thanks for keeping an eye on this!

**Comment by fffinkel** [comment]
Thanks for the quick response!

**Comment by nicolas-s-miller** [comment]
Thanks, @fffinkel for fixing my blunder.

**Pull request merged**
