### PR TITLE
[aws-json] Migrate SNS ListTopics

### PR DESCRIPTION
**Pull request by kojisaikiAtSony**

### CODE REVIEW

**Review by Admiral-Piett — COMMENTED** [review]
Couple tiny things, otherwise looks great!

**Comment by kojisaikiAtSony** [comment]
Ready to merge!

**Comment by Admiral-Piett** [comment]
Looks like something is up with the unit tests on these now?  If we can get that sorted I think they look good to go!

**Comment by kojisaikiAtSony** [comment]
@Admiral-Piett Sorry, fixed the test on ListTopics/DeleteTopic!

**Pull request merged**
