### PR TITLE
allow for queue specific visibility time out configuration

### PR DESCRIPTION
**Pull request by qhenkart**
Currently there can only be a single VisibilityTimeout configuration that affects all queues. However in real life situations, some queues process more complex data than others requiring queue specific VisibilityTimeout settings. This PR simply updates the configuration so that queue specific visibility timeouts are also accepted

### CODE REVIEW

**Comment by Admiral-Piett** [comment]
@qhenkart This looks awesome, thank you!  I will merge it shortly to be in the next release.

**Comment by Admiral-Piett** [comment]
@qhenkart I had to make some updates lately - would you mind rebasing this (so git can track the commit back to you and show your fine work 😉 )?  

If you don't want, feel free to have a look at this?  I rebased here - https://github.com/Admiral-Piett/goaws/pull/280.

**Comment by qhenkart** [comment]
@Admiral-Piett thank you!  I will do it right away

**Comment by qhenkart** [comment]
@Admiral-Piett are you using an alternative to Gofmt? I'm seeing a lot of inconsistent spacing and unusual amount of auto format changes in the rebased PR

**Comment by Admiral-Piett** [comment]
@qhenkart No I'm not, but I am reformatting lots of files as I go.  I think it will work itself out eventually, though I know it's an irritant to look at when you're reviewing.

Also, I'm going to close this.  I'm sorry - I didn't notice your response until I after I merged this one - https://github.com/Admiral-Piett/goaws/pull/280.   It should have been just a rebase of yours anyway.  If there's anything I missed or anything I misrepresented let's talk?

**Comment by Admiral-Piett** [comment]
This was rebased and merged in an alternate PR: https://github.com/Admiral-Piett/goaws/pull/280

**Pull request closed without merging**
