### PR TITLE
Update permissible SNS endpoint call response codes

### PR DESCRIPTION
**Pull request by nicolas-s-miller**
https://docs.aws.amazon.com/sns/latest/dg/SendMessageToHttp.prepare.html

When an SNS subscription calls its endpoint, Amazon recognizes responses in the range of 200-499 as successful Notification deliveries. Responses outside of that range will trigger the Subscription's retry policy.

This PR updates the `callEndpoint` method to allow this range instead of just response codes divisible by 200.

### CODE REVIEW

**Comment by YixingCheng** [comment]
Wanted to make the same change.

**Review by Admiral-Piett — APPROVED** [review]
Good catch!  Looks good to me, thanks @nicolas-s-miller.

**Comment by nicolas-s-miller** [comment]
I don’t have `write` access to merge this. What happens next? No rush. I’m just curious.

**Comment by dhumphreys01** [comment]
Hm, still figuring out how all this is set up.  I'll take a look at the settings for the future but of course, I merged it for now!  Thanks again for having a look at this!

**Comment by fffinkel** [comment]
This merge broke the app. Submitted #256 with the fix.

**Pull request merged**
