### PR TITLE
[aws-json] Migrate SQS GetQueueUrl

### PR DESCRIPTION
**Pull request by kojisaikiAtSony**

### CODE REVIEW

**Comment by kojisaikiAtSony** [comment]
(Now fixing...)

**Comment by kojisaikiAtSony** [comment]
Hi @Admiral-Piett could you please review this?

**Review by Admiral-Piett — APPROVED** [review]
Lovely!

**Comment by Admiral-Piett** [comment]
Sorry, may need a rebase though?  I just merged my purge queue.

**Comment by kojisaikiAtSony** [comment]
You can merge!

**Comment by Admiral-Piett** [comment]
Excellent, thank you!

**Pull request merged**
